export const SQUARES_PER_ROW = 8;
export const POSITIONS_PER_ROW = SQUARES_PER_ROW / 2;
export const ROWS_PER_CHECKERBOARD = 8;
export const POSITIONS_PER_CHECKERBOARD = POSITIONS_PER_ROW * ROWS_PER_CHECKERBOARD;
