// types of highlights for positions on the checkerboard
export const POTENTIAL_MOVER_HIGHLIGHT = 'POTENTIAL_MOVER_HIGHLIGHT';
export const SELECTED_PIECE_HIGHLIGHT = 'SELECTED_PIECE_HIGHLIGHT';
export const POTENTIAL_MOVE_HIGHLIGHT = 'POTENTIAL_MOVE_HIGHLIGHT';
